name: Typescript Compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tsc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install Node.js dependencies
        run: npm install

      - name: Compile Typescript Files
        uses: icrawl/action-tsc@v1
